---
- name: 0.系统初始化
  gather_facts: false
  hosts: all 
  roles:
    - common
  tags: common 

- name: 1.自签证书 
  gather_facts: false
  hosts: localhost 
  roles:
    - tls
  tags: tls

- name: 2.部署Nginx负载均衡并高可用
  gather_facts: false
  hosts: lb
  roles:
    - nginx
  tags: nginx

- name: 3.部署containerd
  gather_facts: false
  hosts: k8s
  roles: 
    - containerd
  tags: containerd 

- name: 4.部署ETCD集群
  gather_facts: false
  hosts: etcd
  roles:
    -  etcd
  tags: etcd

- name: 5.部署K8S Master
  gather_facts: false
  hosts: master
  roles:
    - master
  tags: master

- name: 6.部署K8S Node
  gather_facts: false
  hosts: k8s 
  roles:
    - node
  tags: node

- name: 7.部署插件
  gather_facts: false
  hosts: master
  roles:
    - addons
  tags: addons

- name: 8.部署k9s
  gather_facts: false
  hosts: k9s
  roles:
    - k9s
  tags: k9s