- name: "生成flannel部署文件"
  template:
    src: "{{item.src}}"
    dest: "{{item.dest}}"
  with_items:
    - {src: "flannel.yaml.j2", dest: "/home/flannel.yaml"}
  tags: flannel

- name: "部署flannel"
  shell: "kubectl apply -f /home/flannel.yaml"
  delegate_to: "{{ groups['master'][0] }}"
  run_once: true
  tags: flannel
